Repository arunaengine/website, pull requests merged in 2024-07, with the labels that each got.

#88 Fix search result pagination
  pages/explore.vue
Labels: fix

#89 Fix mailing list registration
  package.json
  server/api/newsletter_register.post.ts
  server/middleware/intercept.ts
  server/routes/auth/refresh.get.ts
Labels: fix

#90 Aruna news and announcements
  README.md
  assets/imgs/blog_blog.webp
  assets/imgs/blog_maintenance.webp
  assets/imgs/blog_orga.webp
  assets/imgs/blog_release.webp
  assets/imgs/blog_update.webp
  components/card/news.vue
  components/navigation/sidebar.vue
  components/navigation/top.vue
  composables/api_wrapper.ts
  composables/aruna_api_json/core/OpenAPI.ts
  composables/aruna_api_json/index.ts
  composables/aruna_api_json/models/v2Announcement.ts
  composables/aruna_api_json/models/v2AnnouncementType.ts
  composables/aruna_api_json/models/v2GetAnnouncementResponse.ts
  composables/aruna_api_json/models/v2GetAnnouncementsByTypeResponse.ts
  composables/aruna_api_json/models/v2Handshake.ts
  composables/aruna_api_json/models/v2PageRequest.ts
  composables/aruna_api_json/models/v2PullReplicationResponse.ts
  composables/aruna_api_json/models/v2Skip.ts
  composables/aruna_api_json/services/StorageStatusServiceService.ts
  composables/enum_conversions.ts
  composables/utils.ts
  nuxt.config.ts
  package.json
  pages/articles/[id].vue
  pages/news.vue
  server/api/announcement.get.ts
  server/api/announcements.get.ts
  server/middleware/intercept.ts
Labels: enhancement

#91 Customizable Info Banner
  app.vue
  components/toast/info.vue
  nuxt.config.ts
  pages/articles/[id].vue
Labels: enhancement

#84 Add alternative downloadlinks to objects
  components/card/downloads.vue
  composables/api_wrapper.ts
  composables/enum_conversions.ts
  composables/proto_conversions.ts
  pages/objects/[id].vue
Labels: enhancement

#92 feat: add button to create a child resource
  composables/enum_conversions.ts
  pages/objects/[id].vue
  pages/objects/create.vue
Labels: enhancement

#94 Enhance article rendering and delivery performance
  components/card/name.vue
  components/card/news.vue
  components/card/small_info.vue
  components/card/stats.vue
  composables/api_wrapper.ts
  composables/utils.ts
  nuxt.config.ts
  package.json
  pages/articles/[id].vue
  server/api/announcement.get.ts
  server/utils/announcement.ts
Labels: enhancement, refactor
